export const citys = [
    'London',
    'Tokyo',
    'Delhi',
    'Shanghai',
    'São Paulo',
    'Mexico City',
    'Cairo',
    'Mumbai',
    'Beijing',
    'Dhaka',
    'Osaka',
    'New York',
    'Karachi',
    'Buenos Aires',
    'Chongqing',
    'Istanbul',
    'Kolkata',
    'Manila',
    'Lagos',
    'Rio de Janeiro',
    'Tianjin',
    'Kinshasa',
    'Guangzhou',
    'Los Angeles',
    'Moscow',
    'Shenzhen',
    'Lahore',
    'Bangalore',
    'Paris',
    'Bogotá',
    'Jakarta',
    'Chennai',
    'Lima',
    'Bangkok',
    'Seoul',
    'Nagoya',
    'Hyderabad',
    'Tehran',
    'Chicago',
    'Chengdu',
]
